### PR TITLE
Refactor to use f-strings

### PR DESCRIPTION
**Pull request by toh995**
Reference for f-strings:
- https://realpython.com/python-f-strings/#simple-syntax
- https://www.python.org/dev/peps/pep-0498/

### CODE REVIEW

**Comment by pluja** [comment]
Have you tested it already? Currently I can't test it and I won't be able to until tomorrow or the day after. If someone can confirm this works I will merge it today.

**Comment by FireMasterK** [comment]
I have not, I'll test this if I can today 👍

**Comment by toh995** [comment]
Thanks guys! Unfortunately I haven't been able to get the full version up and running locally on my machine (haven't looked into setting it up with nginx and everything yet).

However, I did do a quick smoke test and I didn't see any issues so far.

**Comment by toh995** [comment]
Any updates on this? :)

**Comment by FireMasterK** [comment]
I've been unable to review this unfortunately due to lack of time, @pluja could you review this?

**Comment by pluja** [comment]
I think this week I'll have more time, so I'll be reviewing this soon!

**Comment by FireMasterK** [comment]
I did build this on docker for pypy, something seems to be broken there, not sure if it's because of the PR tho.

I'll see if it works on the CPython build.

Edit: Oops, I tested incorrectly by mounting the ports incorrectly. Testing it again.

**Comment by FireMasterK** [comment]
From quick testing, it looks good to me. Everything works fine, even pypy.

**Comment by pluja** [comment]
I also have been able to quick test it, everything looking fine. I'm merging this.

**Pull request merged**
