### PR TITLE
Update README.md no more git.rip

### PR DESCRIPTION
**Pull request by aljaxus**
"Update" the git.rip address as the domain has been seized by FBI

### CODE REVIEW

**Comment by FireMasterK** [comment]
Interesting that the server is still up 🤔 likely due to it being in Russia.

The ssl certificate is broken tho..

If the purpose is just to mirror the repository for backups, I could setup a mirror at git.kavin.rocks @pluja

**Comment by pluja** [comment]
If you could set a mirror it would be great @FireMasterK!

**Comment by FireMasterK** [comment]
@pluja here you go https://git.kavin.rocks/kavin/Yotter

**Comment by pluja** [comment]
Thank you!! how nice!! :D

**Comment by aljaxus** [comment]
If needed, I can also create a mirror @ https://gitplac.si

**Comment by pluja** [comment]
@aljaxus feel free to create a mirror if it is not a problem for you! It is always good to have different and distributed sources and backups :) Thank you!

**Pull request merged**
