### PR TITLE
Simplify import process.

### PR DESCRIPTION
**Pull request by 0ihgk1uVBLlTBzVo7F9B**
Imports have been unified under the youtube option.
The file is just being scanned for a channel id or a channel name and doesn't care for a format anymore.
For clarification there is a tooltip.

yotter_import

ytorg/Yotter#79

### CODE REVIEW

**Comment by pluja** [comment]
Thanks! Awesome.

**Comment by pluja** [comment]
I was thinking if, instead of Youtube, "Others"  would be better?

**Comment by 0ihgk1uVBLlTBzVo7F9B** [comment]
Yeah that does sound better. I would add youtube to the tooltip then.
Will include it in the next pr.

**Comment by pluja** [comment]
Perfect!

**Pull request merged**
